# Generated by Django 5.1.1 on 2024-09-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbhs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('form', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='assignment/')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
