# Generated by Django 5.1.1 on 2024-09-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbhs', '0002_assignment_delete_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='file',
        ),
    ]
