# Generated by Django 5.1.1 on 2024-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbhs', '0003_remove_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(default='assignment/default.pdf', upload_to='assignment/'),
        ),
    ]
